task_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^tasks/', include('tasks.urls')),
    url(r'^admin/', admin.site.urls),
]

tasks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newGroup', views.newGroup, name='newGroup'),
    url(r'^(?P<group_id>[0-9]+)/newTask', views.newTask, name='newTask'),
    url(r'^(?P<group_id>[0-9]+)/(?P<task_id>[0-9]+)/updateTask', views.updateTask, name='newTask'),
    url(r'^(?P<task_id>[0-9]+)/deleteTask', views.deleteTask, name='deleteTask'),
]

tasks/models.py
from django.db import models

class Group(models.Model):
	title = models.CharField(max_length=200)
	def __str__ (self):
		return self.title

class Task(models.Model):
	STATUS = (
		('done', 'done'),
        ('pending', 'pending'),
	)
	title = models.CharField(max_length=200)
	status = models.CharField(max_length=1, choices=STATUS, default='pending')
	group = models.ForeignKey(Group, on_delete=models.CASCADE)
	creation_date = models.DateTimeField('date created', auto_now_add=True)
	def __str__ (self):
		return self.title

tasks/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse, Http404, HttpResponseRedirect

from .models import Task, Group

def index(request):
	groups=Group.objects.all()
	return render(request,'tasks/index.html',{ 'groups' :groups })

def newGroup(request):
	Group.objects.create(title=request.POST["name"])
	return HttpResponseRedirect('/tasks')

def newTask(request, group_id):
	Task.objects.create(title=request.POST["name"],group=get_object_or_404(Group,pk=group_id))
	return HttpResponseRedirect('/tasks')

def updateTask(request, group_id, task_id):
	group=get_object_or_404(Group,pk=group_id)
	task= get_object_or_404(Task,pk=task_id)
	if request.POST["radio"]=="1" :
		task.status="pending"
	else:
		task.status="done"
	task.save()
	return HttpResponseRedirect('/tasks')

def deleteTask(request, task_id):
	task = get_object_or_404(Task,pk=task_id)
	if task.status == "pending":
		task.delete()
	
	return HttpResponseRedirect('/tasks')

tasks/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" >
  </head>
  <body>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
  </body>
</html>

tasks/templates/tasks/index.html
{% extends 'layout.html' %}
<head>
<style>
	ul#form.list-group li{
    	display:inline;
	}

</style>
</head>
{% block content %}
<div class="container">
  <h2>Groups</h2>
	<ul class="list-group">
		{% for group in groups %}

		    <li class="list-group-item">
		    	<a data-toggle="collapse" data-target="#demo_{{ group }}" href="#collapse">{{ group }}</a>
		    </li>
		    <div id="demo_{{ group }}" class="collapse">
			    <li class="list-group-item">
			    	{% for task in group.task_set.all %}
			    			
					    		<ul class="list-group" id="form">
					    				<h2>{{task.id}}</h2>
										<li class="list-group-item">{{task}}</li>
										<li class="list-group-item">{{task.creation_date}}</li>
										</br>											
										<li class="list-group-item">
											<form action="/tasks/{{ group.id }}/{{task.id}}/updateTask" method="post">
												{% csrf_token %}
	  											
  												{% if task.status == "pending" %}
  												<div class="custom-controls-stacked">
  													<label class="custom-control custom-radio">	
	    												<input type="radio" id="radioStacked3" name="radio" value="1" class="custom-control-input" checked>
	    												<span class="custom-control-indicator"></span>
    													<span class="custom-control-description">pending</span>
    												</label>
    											
    											
    												<label class="custom-control custom-radio">
	    												<input type="radio" id="radioStacked4" name="radio" value="2" class="custom-control-input" >
	    												<span class="custom-control-indicator"></span>
	    												<span class="custom-control-description">done</span>
	    											</label>

    											</div>
    											<div>
	    											<button type="submit" class="btn btn-primary">Update</button>
	    											
	  											</div>
    											{% else %}
    											<div class="custom-controls-stacked">
    												<label class="custom-control custom-radio">
	    												<input type="radio" id="radioStacked3" name="radio" value="1" class="custom-control-input">
	    												<span class="custom-control-indicator"></span>
	    												<span class="custom-control-description">pending</span>
	    											</label>
    												
    											
    											
    												<label class="custom-control custom-radio">
	    												<input type="radio" id="radioStacked4" name="radio" value="2" class="custom-control-input" checked>
	    												<span class="custom-control-indicator"></span>
	    												<span class="custom-control-description">done</span>
	    											</label>
    												
    											</div>
    											<div>
	    											<button type="submit" class="btn btn-primary">Update</button>
	    				
	  											</div>
    											{% endif %}


											</form>
										</li>
										<li class="list-group-item"><a href="/tasks/{{ task.id }}/deleteTask" class="btn btn-primary">Delete</a></li>
								</ul>

					{% endfor %}
			    </li>
			    <li class="list-group-item" id="show">
			    <h2>Add new task</h2>								
					<form action="/tasks/{{ group.id }}/newTask" method="post">
						{% csrf_token %}
						<div class="form-group">
							<label for="name">Name:</label>
		    				<input type="text" name="name" />
		    			</div>
		  					</br>
		  				<div>
							<button type="submit" id="add" class="btn btn-primary">Add</button>
						</div>
					</form>						
				</li>
			</div>

		{% endfor %}
	</ul>
	</br>	
	<h2>Add new group</h2>
	<form action="/tasks/newGroup" method="post">
		{% csrf_token %}
		<div class="form-group">
			<label for="name">Name:</label>
    		<input type="text" name="name" />
    		
		</div>

			<button type="submit" class="btn btn-primary">Add</button>
		
	</form>
		
	
</div>



{% endblock %}